### ISSUE TITLE
Cannot build u-boot: "Error: creating /etc/mtab symlink: value too large for defined data type"

### ISSUE THREAD

**Issue by frka1204** [radxa-repo/bsp#119]
I cannot build u-boot for Radxa CM5:

```
./bsp --no-prepare-source u-boot rknext radxa-cm5-io
'docker' backend is selected, but the functionality is actually provided by 'podman' backend. Updating accordingly...
Trying to pull ghcr.io/radxa-repo/bsp:main...
Getting image source signatures
Copying blob 34086a0c1cc9 skipped: already exists  
Copying blob 0a7a0c2c50e9 skipped: already exists  
Copying blob 1874e107f449 skipped: already exists  
Copying blob 29f873e2e3f8 skipped: already exists  
Copying config 5e2d53934c done   | 
Writing manifest to image destination
5e2d53934c4d9706d3ae5baeb1d9aa96356f8ceb163a1c1f5d33a540d7b09b7d
Error: creating /etc/mtab symlink: value too large for defined data type
bsp

```

It seems that line 57 in container.sh fails:
`if ! $CONTAINER_BACKEND run "${CONTAINER_OPTIONS[@]}" "${CONTAINER_REGISTRY}bsp:builder" bash -c "\"$0\" --native-build ${ARGV[*]}"`

The corresponding command seems to be:
`/usr/bin/podman run --name bsp --workdir /home/fredrik/bsp --mount type=bind,source=/home/fredrik/bsp,destination=/home/fredrik/bsp -it --user root ghcr.io/radxa-repo/bsp:builder bash -c ./bsp --native-build --no-prepare-source u-boot rknext radxa-cm5-io bsp`

**Comment by RadxaYuntian** [comment]
Seems to be [host related issue](https://github.com/moby/moby/issues/24837#issuecomment-238293137). What's your running environment?

**Comment by frka1204** [comment]
uname -a
Linux fredrik-desktop 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Everything worked nicely before I decided to reboot the computer.

**Comment by RadxaYuntian** [comment]
Maybe check your `dmesg` to see if there is any error message. You can also try `podman system reset` to reset podman data after you backup important information.

**Comment by frka1204** [comment]
Ok, so `podman system reset` solved the problem
