### ISSUE TITLE
radxa zero 3 bsp not booting

### ISSUE THREAD

**Issue by JohnDGodwin** [radxa-repo/bsp#125]
I'm building a custom kernel as per [these instructions](https://docs.radxa.com/en/zero/zero3/low-level-dev/kernel) and installing the resulting header and image deb files to an image I build with rsdk.
After installing the headers and image deb files, the image fails to boot.

I'm pulling the source with `./bsp -C --no-build linux rk356x`
Then I go into `.src/linux` and `make menuconfig`
I go back to the bsp subdirectory and run `./bsp --dirty linux rk356x -r 999`
The completes, and I install the headers and image files to my rsdk image, which then fails to boot.

**Comment by RadxaYuntian** [comment]
1. does the rsdk image boot without installing your custom images?
2. does the image boots if you don't make modification?

**Comment by JohnDGodwin** [comment]
1. Yes the rsdk image boots without installing my custom kernel.
2. I will compile a test kernel without my modifications and see if it boots.

The only modification I am doing to the kernel is enabling support for a wireless network card, a device driver.

**Comment by RadxaYuntian** [comment]
OK one issue might be if you are literally running `make menuconfig`. You will need to at least do `make ARCH=arm64 menuconfig`.

You can compare `.config` and `.config.old` to see the difference.

**Comment by JohnDGodwin** [comment]
Thank you, passing ARCH=arm64 fixed the issue and I was able to get my wireless card working.
