### ISSUE TITLE
./bsp linux latest fails with scripts/basic/fixdep: Exec format error

### ISSUE THREAD

**Issue by RicoKirstein** [radxa-repo/bsp#32]
Hi, i was unable to get the build script working on a amd64 machine for cross compiling.
In my opinion in the lib/linux.sh script the HOSTCC should not be  the cross compiler, CC should. 

HOSTCC=gcc CC=${CROSS_COMPILE}gcc

Is it working for you on non arm devices?

**Comment by RadxaYuntian** [comment]
This is due to a known issue in Linux source that cross compiled Linux header doesn't work on the target device, as those host tools are built in native format. Just for the record I haven't tried running `bsp` on ARM devices, as our official kernels are all built on GitHub Actions, which support x64 only. Our development workstations are also x64 so \shrug.

You will need to set up support for foreign arch. For Debian/Ubuntu please check [this command](https://github.com/radxa-repo/bsp/blob/main/action.yaml#L30).

**Comment by MikkelSnitker** [comment]
I've installed all the deps (listed in the docker file and the command you linked to) but I still get the same error (scripts/basic/fixdep: Exec format error) 

My host env is amd64/x86. 
If I change the HOSTCC to gcc it compiles fine, but the compiled headerfiles are not arm64 but amd64/x86

Any suggestions ?

Regard Mikkel

**Comment by RicoKirstein** [comment]
You need to install the binfmt support. I got it working that way:
sudo apt-get install --no-install-recommends -y qemu-user-static binfmt-support
Or in manjaro/arch the package is qemu-user-static-binfmt

**Comment by MikkelSnitker** [comment]
I did install those packages:

```
 apt-get install --no-install-recommends -y qemu-user-static binfmt-support
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
binfmt-support is already the newest version (2.2.1-1+deb11u1).
qemu-user-static is already the newest version (1:5.2+dfsg-11+deb11u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

but I'm still getting:

```
root@msn-migration:~/data/bsp# ./bsp -n linux latest
~/data/bsp/.src/linux ~/data/bsp
Reinitialized existing Git repository in /root/data/bsp/.src/linux/.git/
remote: Finding sources: 100% (1/1)
remote: Total 1 (delta 0), reused 1 (delta 0)
Unpacking objects: 100% (1/1), 807 bytes | 807.00 KiB/s, done.
HEAD is now at 129c15b60 Linux 6.1.12
...

make: Entering directory '/root/data/bsp/.src/linux'
  HOSTCC  scripts/basic/fixdep
/bin/sh: 1: scripts/basic/fixdep: Exec format error
make[1]: *** [scripts/Makefile.host:111: scripts/basic/fixdep] Error 126
make[1]: *** Deleting file 'scripts/basic/fixdep'
make: *** [Makefile:633: scripts_basic] Error 2
make: Leaving directory '/root/data/bsp/.src/linux'
`
``

**Comment by RicoKirstein** [comment]
Have you tried running it with -C for clearing out past compiled files?
It might have some corrupt objects when changing the HOSTCC back and rebuilding.

**Comment by MikkelSnitker** [comment]
Yes, I deleted the entire bsp folder at re-cloned it. 

same result

**Comment by RicoKirstein** [comment]
Have you rebooted after installing binfmt-support? As i understand it, it creates some kind of service, maybe that did not come up correctly.

**Comment by RadxaYuntian** [comment]
Please add yourself to `docker` group, re-log in the account, and run the command in normal user. In Debian it should be `sudo adduser $USER docker`.

**Comment by MikkelSnitker** [comment]
no didn't reboot since i'm running in a k8s env

**Comment by RicoKirstein** [comment]
can you run modprobe binfmt_misc to check if the module is loaded?
