### ISSUE TITLE
ROCK5B PSI is turned off by default，Android Docker is still unavailable

### ISSUE THREAD

**Issue by kingwho** [radxa-repo/bsp#55]
ROCK5B PSI is disabled by default, and Android Docker is still unavailable. Please disable this option to enable PSI by default。
![image](https://github.com/radxa-repo/bsp/assets/42891215/2e3576ec-ae4c-4f71-bb5c-d731bb85e55a)

**Comment by RadxaYuntian** [comment]
You could enable PSI by adding the boot parameter. Edit `/etc/kernel/cmdline` and add `psi=1`, then run `sudo u-boot-update` and reboot.
