### ISSUE TITLE
How to install compiled u-boot?

### ISSUE THREAD

**Issue by BigMuscle85** [radxa-repo/bsp#65]
I used bsp to build u-boot with custom modifications but my question is how to actually install it when running on eMMC (Rock 4B+)?

I used the following command to build: `./bsp --no-config --no-prepare-source u-boot latest rock-pi-4b-plus`
It produced u-boot-latest_2023.07.02-1_arm64.deb file that I copied to device and installed using `sudo apt install ./u-boot-latest_2023.07.02-1_arm64.deb`
But this does not install the new u-boot. When I run rsetup, the menu items "Update bootloader" and "Update eMMC boot partition" returns error "No compatible bootloader is available".

I found a command `sudo usr/lib/u-boot/rock-4se/setup.sh update_bootloader /dev/sdX` here https://radxa-repo.github.io/bsp/firmware/update.html but what is the correct partition for updating u-boot on eMMC? Or better - what's the safest way?

```
rock@rock-pi-4b-plus:~$ ls /dev/mmc*
/dev/mmcblk0  /dev/mmcblk0boot0  /dev/mmcblk0boot1  /dev/mmcblk0p1  /dev/mmcblk0p2  /dev/mmcblk0p3  /dev/mmcblk0rpmb
```

The second question... now when I run `sudo apt update && sudo apt upgrade` it reinstall the version from the APT repository. When this happens, does it update packages only or does it update u-boot on eMMC ?

**Comment by RadxaYuntian** [comment]
`rsetup` issue is fixed in https://github.com/radxa-pkg/rsetup/commit/d7d75fc0e95c128c3312df8ee36079520b246617. I have a few other issues pending for it, so once I wrap them up I'll create a new release.

**Comment by RadxaYuntian** [comment]
`rsetup` 0.3.29 has been [released](https://github.com/radxa-pkg/rsetup/releases/tag/0.3.29). It will go into our test channel first, so for now you could download `rsetup_0.3.29_all.deb` and install it on your system with `sudo dpkg -i rsetup_0.3.29_all.deb` command.

**Comment by BigMuscle85** [comment]
Thank you. Now it works correctly.
