### ISSUE TITLE
Missing symbols in compiled DTBs in "latest" -> not working overlays

### ISSUE THREAD

**Issue by pavhofman** [radxa-repo/bsp#84]
While the "stable" variant of linux compilation applies a patch which appends '-@' to the DTC_FLAGS_xxx to generate symbols for overlays https://github.com/radxa-repo/bsp/blob/main/linux/.stable-6.1/0100-vendor/0001-VENDOR-Add-Radxa-overlays.patch , the "latest" variant has no such patch. As a result compiled dtb's lack the symbols and overlays (which typically use the symbols) do not work.

**Comment by RadxaYuntian** [comment]
The `latest` variant is intended for testing and development, so it does not contain our custom patches, since keeping them up to date for build to pass takes some effort. For now only officially supported variants will contain the full patch set.

**Comment by pavhofman** [comment]
Thanks for the info. Please would you consider adding the information about missing symbols being compiled in  + how to fix that in the arch/arm64/boot/dts/rockchip/Makefile somewhere to your bsp (wiki of github)? It's quite difficult to troubleshoot as it requires serial connection to see the uboot error. Thank for considering.
