### ISSUE TITLE
compile on x86 linux

### ISSUE THREAD

**Issue by idreamerhx** [radxa-repo/bsp#90]
following: https://docs.radxa.com/rockpi/rocks0/low-level-dev/kernel

[root@xxxxx bsp]# git diff lib/linux.sh
diff --git a/lib/linux.sh b/lib/linux.sh
index 7b2a56f..b822ba4 100644
--- a/lib/linux.sh
+++ b/lib/linux.sh

     make -C "$TARGET_DIR" -j$(nproc) \
-        ARCH=$BSP_ARCH CROSS_COMPILE=$CROSS_COMPILE HOSTCC=${CROSS_COMPILE}gcc \
+        ARCH=$BSP_ARCH CROSS_COMPILE=$CROSS_COMPILE HOSTCC=gcc \
         KDEB_COMPRESS="xz" KDEB_CHANGELOG_DIST="unstable" DPKG_FLAGS=$BSP_DPKG_FLAGS \
         LOCALVERSION=-$PKG_REVISION-$FORK KERNELRELEASE=$kernelversion-$PKG_REVISION-$FORK KDEB_PKGVERSION=$kernelversion-${PKG_REVISION}${SOURCE_GITREV:+-$SOURCE_GITREV} \
         $@

**Comment by RadxaYuntian** [comment]
> following: https://docs.radxa.com/rockpi/rocks0/low-level-dev/kernel

You probably did not follow https://radxa-repo.github.io/bsp/ which is linked in the above page.
