### ISSUE TITLE
Unable to boot from NVME

### ISSUE THREAD

**Issue by BigMuscle85** [radxa-repo/bsp#99]
I don't know if it is officially supported but we have a whole system image on NVME while eMMC contains only U-Boot on ROCK 4B+ board. We use SSD Samsung EVO 980.
System is installed to eMMC via OTG port and then the whole eMMC is copied with 'dd' command to SSD. Subsequently, all eMMC partitions are deleted with fdisk, the eMMC bootloader is updated and SSD resized with 'resize2fs'. It worked correctly until the following change:
https://github.com/radxa-repo/bsp/blob/350af0b1d6c996668a30ae1b3791282dbe48a49c/u-boot/latest/fork.conf#L47

With this change, U-Boot does not load system from NVME at all and ends up in an infinite reboot loop. It seems that disabling PCI in U-Boot also disables the bus where NVME is connected to. After enabling CONFIG_PCI, it boots correctly again.

**Comment by RadxaYuntian** [comment]
The reason was well explained in [this comment](https://github.com/radxa-repo/bsp/commit/7e13bf757e1e69352f2b9b09c1a0a1c0290b234d). Anyway since we reverted the version to 2023.10 I think I can re-enable those too.
